{% set name = "django-storages" %}
{% set version = "1.7" %}
{% set sha256 = "e021ae94c0ca39c683260fa0065cae0df041d795dd79fee8f7bf4ba31798640d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8

about:
  home: https://github.com/jschneier/django-storages
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'django-storages is a project to provide a variety of storage backends in a single library.'
  description:
    This repo began as a fork of the original library under the package name of django-storages-redux 
    and became the official successor (releasing under django-storages on PyPI) in February of 2016. 
    This library is usually compatible with the currently supported versions of Django. 
    Check the Trove classifiers in setup.py to be sure.
  doc_url: https://django-storages.readthedocs.io/en/latest/
  dev_url: https://github.com/jschneier/django-storages

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
