travis:
  secure:
    BINSTAR_TOKEN: uetnmQ0Ne0jd1TAf2L/Qpe/nPOh7FGKCvl9mCDQMHczbbzG++VOa1qi4t1tBtR8LvHGNad4IwNCJsYfbuK+Ty01TfnYE0Z597ONp38T3/fQDY8abPoMiD2K/EizJQo3shsMfBdnGD1nda8CdwmdRe3nQMmEJf98nVIV9qi9MR5tHXasfHjtOvvv6FtGTvqWHG7NZhAgOxJwrrJNB2Dv4QJQ35gOUf4OP/MXDfOXnIFxDshvfWo8gKMw5AOBUglYgz0oYigNgfYX4lQRxSFSTpJM+QzmxjP05/CkberAGgE6j4QyosspLzy7qv2l97rYkEJ9+UAsHDU62oiN19dozse3J4n69QNfkO0zx/PwEo7mz6bS6P/6nR7IS/KshTYu17vu8KSiO58P4QF91D3JGPt0ajphVRYtqJCxNFmLh1vBuWSobpbYG9QmpVNhyjh9LDsPQ7k71zGhEIaDVQ3fC9to91B0D3+YQnXx9zcUi/+CUAVuprDVGnufIuIYTRANRmssw9MwrjLLJ2epkbf2MEJ2ZhSecbtVa1jzk1bEHkHthQrGhNHFsTzEVpY2GCRbe0e3+aAPNB1+1w8mN21szgDk9nQfL9qVfvspX3i/dG4aicwKNTGsa23vOYuXq0ik3LvP+z/QXKZ4EvPpEUEFX27YurfKqPhBU/63DNvw2qDg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
