travis:
  secure:
    BINSTAR_TOKEN: FsgVFnstanDQRSMchT71xuStEhyBtcw9rgtnh5lzh2N/6Nd+CBkWU/UVJJAwrd8HwhO9s4/w5tNsK8T6phsxoG2ARnyWppTDXulObyV8KuomN6VpSEMHzSxL1dQ/82MA8CH60DTNW7GIhQVgh/cWAYmdGCPfFoyRMLbHh5ReqXyloY9RnbJjrNyP9OZ6zUiLfmsm+LHNQ0xBXDnjw0nGtoQa9xyP9ftISBcpfaH+idfB3qtC97WwfRKiKfbhMzGbsOTyD74InXTaEW6VjAJTUCw8rVM+8xusfgn6+IotE55C8zPkcnxcs8eK5KinZ53RWWduKDmwGkbSY9xpPm/dm4qrtb53hUVZrFZOb4kkjJe3GVAj1RYltKlNOoVfoA2qVO5sWRIfg/NlccAlieWqpfcKR2R2l5DvAzPKtwA5foXYkq8ijwM7HrHN1CpSa/470gw46RhfArUAzOOcjowmDtgbpSs30asZG9FBKzkuL2Eik/PedGTwtYC4nBVFmaMp8zZPcytlQ/2FF5zzcGqkIXurBb+nfGRsAmxYcWHBQEQWtRhNlwoE7SzySZxH284cYUul5snI6aNt/j+dQvejIUGDQ7jK8ar0lTKMnXzKFrBTrUiiITNvqqnX7Wa0ileMvUeAjBhjbd/UGvg2ZXPf/HQkbA8G4GmjdxFLOoAkfmU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
