travis:
  secure:
    BINSTAR_TOKEN: mtUWLRTzZ+lTIHZGE2cFddI92IFrwi0QGzqbuwEPC5vnaI7lf+7WWhu6E5O4nzQISAGft129zuJZ7G77xy8TIbx21fuZBcMMHgO5juy4UBWubfcVR6/MIufB+UASoYH4entNeEYmSKmc1jy4kPZyhmLa8b45RqLeIrl4Nf5Q1LNGNNklUVD2aWb/KPK6jYBhku+vt4aoPU53aXMquSI8iHVOil+xHazs2Vc/lBuS28IZ0WTcrM1/QsWlZtldRln8Uq4FK7SeAPvXPynCler6tFJ4DZ+7BvVOlQvUAT8h6JE9/E4IDRyYjiMauXDWJEBgB3YTEBWTyGjXVcLzIvePmxlDIR8AiAHQJHUbpRNBApWZgSrYiVuJ5i+eFzpJAzlCd+2J35qM4uRM+9AurYHSPpTqdVELBTQ2w4W7ybOY7Nad5r44/LlsdLZfAQ7cnmz7Id7GWp2Ys3ZUm/M7/oSxuPKUnTTvHsJeUfq67E0GOL1qrYlp4rjwAS/SE+09a8dcOaeUpnDZjuvl/h8+6fkxK25W+8qCiMrWF/D2J8SZ2foX6WjcHrGDQ9WJiV6rgJHfvlh5ViJWQ2JsqS8Te4q4iwV1M+kVbEqXrtNZsGAU6HycgJ4BPNanBjMx9DGpQ+McweoSwYpMjNwyBlydIw9tV2FaRZGP0cELru+Ai6w1QLk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
